//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PadronAsociado
    {
        public int id { get; set; }
        public string idExcel { get; set; }
        public string Nombre { get; set; }
        public string Cedula { get; set; }
        public string Estatus1 { get; set; }
        public string Estatus2 { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
        public string Estado3 { get; set; }
        public Nullable<System.TimeSpan> HoraRegistro { get; set; }
        public int idEvento { get; set; }
    
        public virtual tbl_Evento tbl_Evento { get; set; }
    }
}
